name: Beta Feedback
description: Give general feedback about the beta
title: "[Feedback]: "
labels: ["feedback"]
body:
  - type: input
    id: mod-version
    attributes:
      label: Mod version
      placeholder: "0.1.0-beta"
    validations:
      required: true

  - type: textarea
    id: feedback
    attributes:
      label: Feedback
      description: What worked well? What felt confusing? What should change?
    validations:
      required: true